### ISSUE TITLE
Make the email checker actually invalidate invalid emails

### ISSUE THREAD

**Issue by TommyWithATiger** [TommyWithATiger/TOBOT#37]
The current email checker for the user does not really check if an email is valid. We should be following RFC 5322, which defines how this should be done as a standard.

This regex 
```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
````
should follow the standard, and be pretty straight forward to implement. Will need to implement new tests to check if the code works, as the current email tests in user will fail.

**Comment by PhilipPuente** [comment]
Added to userType patch
