### ISSUE TITLE
Error when ranking some topics

### ISSUE THREAD

**Issue by PhilipPuente** [TommyWithATiger/TOBOT#80]
![image](https://cloud.githubusercontent.com/assets/15088360/24241817/5cc7cf8a-0fb6-11e7-99c7-ded8bdd9f2ec.png)

**Comment by EspenHa** [comment]
Seems like the frontend is sending the topic IDs as numeric strings.
![bug](https://cloud.githubusercontent.com/assets/8143383/24272324/14f438f8-101d-11e7-8bf7-8922df3d4c3d.png)
